### PR TITLE
JSON.lua up to date; add array_newline option;

### PR DESCRIPTION
**Pull request by yurenchen000**

### CODE REVIEW

**Comment by tiye** [comment]
Actually I'm not a Lua user. So I think we need another people to review the PR. Can you suggest someone?

**Comment by yurenchen000** [comment]
@jiyinyiyong 
unfortunately, the orignal code author not play github 
┑(￣Д ￣)┍

**Comment by tiye** [comment]
Trying random users on GitHub trending... @junyanz @cloudwu @meric

**Comment by tiye** [comment]
Merged without a review...

**Pull request merged**
